name: Release Binary

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write 

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o host-reporter-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o host-reporter-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o host-reporter-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o host-reporter-windows-arm64.exe
          GOOS=darwin GOARCH=amd64 go build -o host-reporter-mac-amd64
          GOOS=darwin GOARCH=arm64 go build -o host-reporter-mac-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            host-reporter-linux-amd64
            host-reporter-mac-amd64
            host-reporter.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
